### ISSUE TITLE
Cannot use python based fv3config.diag_table configurations in this repo

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3gfs-fortran#239]
fv3config supports specifying diag_tables in the yaml ([docs here](https://fv3config.readthedocs.io/en/latest/usage.html#diagtable-configuration)) with the following syntax:
```
name: example_diag_table
base_time: 2000-01-01 00:00:00
file_configs:
- name: physics_diagnostics
  frequency: 1
  frequency_units: hours
  field_configs:
  - field_name: totprcpb_ave
    module_name: gfs_phys
    output_name: surface_precipitation_rate
  - field_name: ULWRFtoa
    module_name: gfs_phys
    output_name: upward_longwave_radiative_flux_at_toa
```

However, I cannot use these options for tests in this repo: https://app.circleci.com/pipelines/github/ai2cm/fv3gfs-fortran/1853/workflows/e5e64175-ea8f-4fca-bdd0-afb037a6adc6/jobs/2807?invite=true#step-115-2770

The installed version of fv3config should support this. I'm not sure what the problem is...maybe there are some zombie fv3config  versions installed here.

cc @mcgibbon @ofuhrer
